name: Build and deploy Python app to Azure Web App - MDC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7B917D6CC14D4D38ABB0E901F464D816 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E198EA4DCAA548D0A58FB04EB70C431E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6FEC00BEEEB4D0AAC7880972F9A0E62 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MDC'
          slot-name: 'Production'
          package: .
